// Generated by generate.py from vendor:raylib 6.0. Do not edit, rerun the script
// after an Odin update.
//
// The easing functions are implemented in Odin, so these compile into the plugin.
package waylib

import rl "vendor:raylib"

EaseLinearNone   :: rl.EaseLinearNone
EaseLinearIn     :: rl.EaseLinearIn
EaseLinearOut    :: rl.EaseLinearOut
EaseLinearInOut  :: rl.EaseLinearInOut
EaseSineIn       :: rl.EaseSineIn
EaseSineOut      :: rl.EaseSineOut
EaseSineInOut    :: rl.EaseSineInOut
EaseCircIn       :: rl.EaseCircIn
EaseCircOut      :: rl.EaseCircOut
EaseCircInOut    :: rl.EaseCircInOut
EaseCubicIn      :: rl.EaseCubicIn
EaseCubicOut     :: rl.EaseCubicOut
EaseCubicInOut   :: rl.EaseCubicInOut
EaseQuadIn       :: rl.EaseQuadIn
EaseQuadOut      :: rl.EaseQuadOut
EaseQuadInOut    :: rl.EaseQuadInOut
EaseExpoIn       :: rl.EaseExpoIn
EaseExpoOut      :: rl.EaseExpoOut
EaseExpoInOut    :: rl.EaseExpoInOut
EaseBackIn       :: rl.EaseBackIn
EaseBackOut      :: rl.EaseBackOut
EaseBackInOut    :: rl.EaseBackInOut
EaseBounceOut    :: rl.EaseBounceOut
EaseBounceIn     :: rl.EaseBounceIn
EaseBounceInOut  :: rl.EaseBounceInOut
EaseElasticIn    :: rl.EaseElasticIn
EaseElasticOut   :: rl.EaseElasticOut
EaseElasticInOut :: rl.EaseElasticInOut
