#!/usr/bin/env python3
"""Generates waylib's re-export files from Odin's vendor:raylib.

Usage: generate.py "$(odin root)/vendor/raylib"

Writes raylib_types.odin (every type plus the colour constants), raymath.odin and
easings.odin (aliases of the pure Odin helper procedures and math constants). The
significant raylib procedures are deliberately not re-exported: those go through the
host, see waylib.odin.
"""
import re
import sys
from pathlib import Path

NAME = r"([A-Z][A-Za-z0-9_]*)"
STRUCTURAL = re.compile(NAME + r"\s*::\s*(?:(?:struct|enum|distinct|bit_set|#row_major|matrix|quaternion\d+|#type proc)\b|\[)")
ALIAS = re.compile(NAME + r"\s*::\s*" + NAME + r"\s*(//.*)?$")
COLOR = re.compile(r"([A-Z]+)\s*::\s*Color\{")
PROC = re.compile(NAME + r"\s*::\s*(#force_inline\s+)?proc\b")
CONSTANT = re.compile(r"(PI|DEG2RAD|RAD2DEG|EPSILON)\s*::")
VERSION = re.compile(r'^VERSION\s*::\s*"([^"]+)"', re.MULTILINE)


def declarations(text, pattern):
	"""Names declared at column 0 matching pattern, skipping ones whose attribute line
	marks them deprecated: Odin's raymath deprecates the helpers that plain operators
	replace, and an alias of one would warn on every plugin build."""
	names = []
	previous = ""
	for line in text.splitlines():
		if (match := pattern.match(line)) and "deprecated" not in previous:
			names.append(match.group(1))
		if line.strip():
			previous = line
	return names


def render(path, version, comment, names):
	width = max(len(name) for name in names)
	lines = [
		f"// Generated by generate.py from vendor:raylib {version}. Do not edit, rerun the script",
		"// after an Odin update.",
		"//",
		f"// {comment}",
		"package waylib",
		"",
		'import rl "vendor:raylib"',
		"",
	]
	lines += [f"{name:<{width}} :: rl.{name}" for name in names]
	path.write_text("\n".join(lines) + "\n")
	print(f"{path.name}: {len(names)} aliases")


def main(raylib_dir):
	raylib = (raylib_dir / "raylib.odin").read_text()
	raymath = (raylib_dir / "raymath.odin").read_text()
	easings = (raylib_dir / "easings.odin").read_text()
	version = VERSION.search(raylib).group(1)

	types = declarations(raylib, STRUCTURAL)
	known = set(types)
	for line in raylib.splitlines():
		if (match := ALIAS.match(line)) and match.group(2) in known:
			types.append(match.group(1))
			known.add(match.group(1))
	colors = declarations(raylib, COLOR)
	math_constants = declarations(raylib, CONSTANT) + declarations(raymath, CONSTANT)

	here = Path(__file__).parent
	render(here / "raylib_types.odin", version,
		"Every raylib type, including the callback types a plugin cannot use, and the named colours.",
		types + colors)
	render(here / "raymath.odin", version,
		"raymath is implemented in Odin, so these compile into the plugin and never reach the host.\n// Helpers that raylib deprecates in favour of operators, such as Vector2Add, are left out.",
		math_constants + declarations(raymath, PROC))
	render(here / "easings.odin", version,
		"The easing functions are implemented in Odin, so these compile into the plugin.",
		declarations(easings, PROC))


if __name__ == "__main__":
	main(Path(sys.argv[1]))
